### ISSUE TITLE
[CICD] 깃 액션 동작 중 도커 컨테이너가 삭제되는 현상

### ISSUE THREAD

**Issue by korogoo** [KUIT-AGARANG/Agarang-Backend#14]
## 어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요

깃 액션이 실행되고 blue -> green 포트로 이동하는 과정 중에 새롭게 생성한 green 컨테이너가 생성 즉시 다시 삭제되는 현상이 발생합니다.

<br/>

## 어떤 상황에서 발생한 버그인가요?

> (가능하면) Given-When-Then 형식으로 서술해주세요

### GIVEN & WHEN

`Docker compose` 에서 컨테이너가 생성됩니다.

`Check deploy server URL` 에서 새로 생성된 포트로 커넥션을 5번 시도합니다.

```yaml
...

- name: Docker compose
  uses: appleboy/ssh-action@master
  with:
    username: ubuntu
    host: ${{ secrets.AGARANG_SERVER_IP }}
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    script_stop: true
    script: |
      sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/agarang:latest
      sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d

- name: Check deploy server URL
  uses: jtalk/url-health-check-action@v4
  with:
    url: http://${{ secrets.AGARANG_SERVER_IP }}:${{env.TARGET_PORT}}/env
    max-attempts: 5
    retry-delay: 10s

...
```

### THEN

![스크린샷 2024-07-14 오전 1 40 36](https://github.com/user-attachments/assets/824f0ac6-77e5-4bd0-b7df-45b1027592d9)

커낵션 5회 실패로 deploy 단계에서 배포 실패가 발생합니다.

<br/>

## 해결과정

해당 부분 현재 해결되었고, git-secrets 설정 관련 문제였기 때문에 별도의 PR 은 생성하지 않았습니다.
자세한 해결과정은 아래 노션 링크 남깁니다! 공유를 위해 이슈는 하루정도 뒤에 닫겠습니다.

<br/>

## 참고할만한 자료(선택)

트러블슈팅 정리한 노션 링크 남깁니다. [트러블슈팅](https://goo99.notion.site/CICD-c6f2dc8243d14a8d97e59031ba01f359?pvs=4)
