### ISSUE TITLE
[CICD] SSL 적용 이후 curl 301 오류

### ISSUE THREAD

**Issue by korogoo** [KUIT-AGARANG/Agarang-Backend#33]
## 어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요

https 를 적용하고나니 기존 배포단계 중 그린 or 블루 포트를 정하는 job 에서 오류가 났습니다.

<br/>

## 어떤 상황에서 발생한 버그인가요?

> (가능하면) Given-When-Then 형식으로 서술해주세요

### GIVEN & WHEN

```yaml
deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set Target IP
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.AGARANG_SERVER_IP }}/env")
          ...
```

### THEN

```
STATUS=$(curl -o /dev/null -w "%{http_code}" "http://EIP.../env"); echo $STATUS;

301
```

<br/>

## 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

```
STATUS=$(curl -o /dev/null -w "%{http_code}" "..."); echo $STATUS;

200
```
200 ok 가 응답되어야 타켓 포트를 정할 수 있습니다.
